# Site settings
title: Intelligent Algorithms
email: admin@domain.com
description: "Free book about machine learning with beautiful interactive figures to explore concepts of predictive data analysis. "
baseurl: ""
url: "http://intelligentalgorithms.org"

# Build settings
permalink: pretty